# Generated by Django 3.1.2 on 2020-10-15 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wrapper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentmessage',
            name='attempt',
        ),
        migrations.RemoveField(
            model_name='sentmessage',
            name='capture_time',
        ),
        migrations.RemoveField(
            model_name='sentmessage',
            name='latency',
        ),
        migrations.RemoveField(
            model_name='sentmessage',
            name='question',
        ),
        migrations.AddField(
            model_name='sentmessage',
            name='end_time',
            field=models.DateTimeField(null=True, verbose_name='time finished'),
        ),
        migrations.AddField(
            model_name='sentmessage',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wrapper.server'),
        ),
        migrations.AddField(
            model_name='sentmessage',
            name='start_time',
            field=models.DateTimeField(null=True, verbose_name='time started'),
        ),
        migrations.AddField(
            model_name='sentmessage',
            name='uuid',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sentmessage',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
