# Generated by Django 3.1.2 on 2020-10-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapper', '0002_auto_20201015_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvalidNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200)),
            ],
        ),
    ]
